Add unit tests for com.linkedin.tony.util.Utils
Diffblue-benchmarks/Linkedin-TonY pull request #1
Opened 2019-07-04 12:05 UTC by Braavos96

I've analysed your codebase and noticed that `com.linkedin.tony.util.Utils` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important in a subsequent PR.

I did move the test methods around so that the test methods are in the same order as the tested methods

I also refactored a few existing `assertEquals` statements to ensure that the `actual` value comes first

2019-07-04 12:09 UTC, JohnLBergqvist requested changes
I would prefer you didn't move the existing stuff around (at least, not in the same commit) as it makes what you've added hard to determine.

2019-07-04 12:15 UTC, Braavos96 commented
> I would prefer you didn't move the existing stuff around (at least, not in the same commit) as it makes what you've added hard to determine.

Ok I moved them back :)

2019-07-04 12:16 UTC, Braavos96 commented on tony-core/src/test/java/com/linkedin/tony/util/TestUtils.java
> +
Not sure why this happens....

2019-07-04 12:16 UTC, Braavos96 commented on tony-core/src/test/java/com/linkedin/tony/util/TestUtils.java
> +
I will clone the project and try again

2019-07-04 12:30 UTC, Braavos96 commented on tony-core/src/test/java/com/linkedin/tony/util/TestUtils.java
> +
Done....

2019-07-04 13:01 UTC, JohnLBergqvist approved these changes

2019-07-04 13:01 UTC, JohnLBergqvist commented
@Braavos96 Split out the changes to their tests into a seperate commit.

2019-07-05 09:22 UTC, paulkennethkent approved these changes

2019-07-05 10:53 UTC, JohnLBergqvist approved these changes

2019-07-11 08:52 UTC, closed without merging